# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertotal_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='passbook',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
