# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passbook_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotal',
            name='account_id',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
